sudo: required

language: generic

services:
    - docker

before_install:
    - echo "start creating an image with dockerfile"
    - docker build -t rladlsvy/single -f Dockerfile.dev .

script:
    - docker run -e CI=true rladlsvy/single npm run test -- --coverage
