name: CI-test

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v2

            - name: Set up Docker
              uses: docker/setup-buildx-action@v1

            - name: Start creating an image with Dockerfile
              run: docker build -t rladlsvy/single -f Dockerfile.dev .

            - name: Run tests
              run: docker run -e CI=true rladlsvy/single npm run test -- --coverage

            - name: Tests Success
              if: success()
              run: echo "Tests success"
